### ISSUE TITLE
Add the support for continuous integration

### ISSUE THREAD

**Issue by rouvoy** [TVerbaere/PFE#3]
You can add a continuous integration support for your project using [TravisCI](https://travis-ci.org) and include the associated [status badge](https://docs.travis-ci.com/user/status-images/) from the home page.

**Comment by TVerbaere** [comment]
[![Build Status](https://travis-ci.org/TVerbaere/PFE.svg?branch=master)](https://travis-ci.org/TVerbaere/PFE) ... hum... Embarrassing !

**Comment by TVerbaere** [comment]
Do I have to add : "exclude: -ant" in the travis file ?

**Comment by rouvoy** [comment]
Why don't you use the [Android support of Travis CI](https://docs.travis-ci.com/user/languages/android)?

**Comment by TVerbaere** [comment]
Ok ! Build success !
During the clean, i delete important files !
