### ISSUE TITLE
Automatically disabling views in Android apps

### ISSUE THREAD

**Issue by rouvoy** [TVerbaere/PFE#5]
The minimal feature to support is to disable [Views](http://developer.android.com/reference/android/view/View.html) (incl. buttons) within an [Android activity](http://developer.android.com/reference/android/app/Activity.html).

Typically, from Javascript, one should be able to write the following code snippet:

``` javascript
var gui = import("gui");
var wifi = import("wifi");

gui.onActivityCreated("MainActivity", function(evt) {
    if (!wifi.isConnected()) {
        gui.viewById("@+id/my_button").setEnabled(false);
    }
});
```

Which implies to define a dedicated facade declared as a Java interface and defining the signatures of the methods `onActivityCreated` and `viewById`.

**Comment by TVerbaere** [comment]
Changed ! Now the script looks like this (i changed import because it's a key word for JAVA) :

```
var gui = importing("gui");
var wifi = importing("wifi");

gui.onActivity('MainActivity', function(){
       if (!wifi.isConnected()) {
              gui.disabledViewwithId('button');
       }
       else {
              gui.enabledViewwithId('button');
       }
});
```

**Comment by rouvoy** [comment]
You miss the `gui.viewById("@+id/my_button").setEnabled(false)` instead of `gui.disabledViewwithId('button')`.

**Comment by TVerbaere** [comment]
Ok, if you prefer... It's changed !
Now you can call :

gui.viewById("@+id/my_button")
or
gui.viewById("my_button").

**Comment by rouvoy** [comment]
Thanks, I included a couple of comments in your latest commit.

**Comment by TVerbaere** [comment]
I saw. I don't understand your second comment.
I have to rename the interface "Facade" into "GuiFacade", declare inside "onActivity" and "viewById" and rename "GuiFacade" into "GuiFacadeImpl", Right ?

**Comment by TVerbaere** [comment]
For the first, it's normal.
I have to convert the View (JAVA) to a Javascript Object.
So the return is an Object (and it cannot be cast to View).

**Comment by rouvoy** [comment]
Exactly

**Comment by TVerbaere** [comment]
So, if I declare "onActivity" and "viewByUd" in the interface, i have to implement these methods in my others facades (Wifi, etc..). I think it's strange no ?

**Comment by rouvoy** [comment]
Obviously, you should have individual interfaces for each `Facade`

**Comment by TVerbaere** [comment]
Ok, it's done.
I let the return of "viewById". Indeed, the return must be compatible with Javascript.

**Comment by rouvoy** [comment]
I'm fine with that, but you should clearly document it as one can expect a `View` object instead of a JSON object.
