### ISSUE TITLE
Disabling a menu item

### ISSUE THREAD

**Issue by rouvoy** [TVerbaere/PFE#6]
(Issue discussed with @magolac)

From a given [Activity](http://developer.android.com/reference/android/app/Activity.html), the [Toolbar](http://developer.android.com/reference/android/support/v7/widget/Toolbar.html) is a special view from which the [Menu](http://developer.android.com/guide/topics/ui/menus.html) object can be retrieved as follows:

``` JavaScript
var menu = gui.viewById("@+id/my_awesome_toolbar").getMenu();
```

From there, a specific [menu item](http://developer.android.com/reference/android/view/MenuItem.html) can be disabled:

``` JavaScript
menu.findItem("@+id/action_notification").setEnabled(false);
```

Please note that one of these methods may return `null` if the associated objects are not created, yet. So you should carefully take into consideration the [menu lifecycle](http://developer.android.com/guide/topics/ui/menus.html#ChangingTheMenu) when calling these functions.

**Comment by rouvoy** [comment]
Can you mention the commit id in your issue?

**Comment by rouvoy** [comment]
1. Why the AspectJ code has to be defined by the App?
2. What is the purpose of intercepting `"execution(* *.onCreate(..))"` and `"call(* *.inflate(..))"` if no code is executed in the advice?
3. When declaring the AspectJ snippet do all the menus are automatically and statically disabled? I did not catch the issue with the `Placebo` object.

**Comment by TVerbaere** [comment]
In build.gradle, it's possible to put an external aspect (aspectPath), I tried without success...
I think it's better to talk about the other questions next friday.

**Comment by rouvoy** [comment]
What about 2. and 3. ?
